#robot_radius: 0.075 # 机器人半径
footprint: [[-0.045, 0.06], [0.105, 0.06], [0.105, -0.06], [-0.045, -0.06]]
footprint_padding: 0.00
footprint_inflation: 0.025 # 机器人膨胀层

transform_tolerance: 2.0

always_send_full_costmap: false  #true

obstacle_layer:
 enabled: true
 obstacle_range: 1.5 # 规避障碍的范围
 raytrace_range: 2.5 # 探测障碍的范围
 inflation_radius: 0.2
 track_unknown_space: true
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}

static_layer:
  enabled:              true
  map_topic:            "map"
