<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="phasespace_calibration_board">

  <!-- a foam cube of given size with one centered apriltag of given 
       marker_size centered on each of the six faces.

       Note that our apriltag textures include the white border around
       the actual pattern (100x100 pixels total, with 80x80 pixels pattern).
       For example, our demo cubes are 70x70x70 mm diameter, and this
       needs to be specified here for marker_size. The apriltags node
       instead want the "internal" size, which is 0.056 (0.07*80/100)  
       in this case.

       2016.08.12 - fnh - rename links to simply pose reconstruction
       2016.07.14 - fnh - created

       for details, see tracknrec_ros/config/trackers.yaml:
 - id: 2
    type: "rigid"
    name: "calibobj_tracker"
    markers:
      - {id: 32, name: "origin_marker", options: "pos=3.5,3.0,3.0"}
      - {id: 33, name: "x_axis_marker", options: "pos=268.951,3.0,3.0"}
      - {id: 34, name: "aux1_marker", options: "pos=269.188,199.116,0.58"}
      - {id: 35, name: "aux2_marker", options: "pos=233.578,235.966,0.0"}
      - {id: 36, name: "y_axis_marker", options: "pos=7.356,234.888,3.0"}

  -->

  <xacro:include filename="$(find tams_apriltags)/urdf/materials.xacro" />
  <xacro:include filename="$(find tams_apriltags)/urdf/utilities.xacro" />
  <xacro:include filename="$(find tams_apriltags)/urdf/apriltag_marker.xacro" />

  <xacro:macro name="phasespace_led" params="parent name size *origin">
    <link name="${name}">
      <origin xyz="0 0 0" />
      <mass value="0.001" />
      <inertia  ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
      <visual>
        <material name="red" /> 
        <origin xyz="0 0 ${-size/2}" />
        <geometry>
          <box size="${size} ${size} ${size}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${-size/2}" />
        <geometry>
          <box size="${size} ${size} ${size}" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${name}">
      <material>Gazebo/RedGlow</material>
      <turnGravityOff>false</turnGravityOff>
      <selfCollide>false</selfCollide>
      <!-- kp: stiffness kd: damping mu1, mu2: friction -->
      <mu1>100.0</mu1>
      <mu2>100.0</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
    </gazebo>
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}"/>
    </joint>
  </xacro:macro>



  <xacro:macro name="phasespace_calibration_board" params="name" >
    <!-- the main board, x=0.24 y=0.275 z=0.01
         Note that we increased the thickness instead of modelling
         the feet separately...
    -->
    <link name="${name}">
      <origin xyz="0 0 0" />
      <mass value="0.001" />
      <inertia  ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.1" />
      <visual>
        <material name="silver" /> 
        <origin xyz="${0.275/2} ${0.240/2} ${0.01/2}" />
        <geometry>
          <box size="0.275 0.240 0.01" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${0.275/2} ${0.240/2} ${0.01/2}" />
        <geometry>
          <box size="0.275 0.240 0.01" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${name}">
      <!-- fuckk <material>Gazebo/Black</material> -->
      <turnGravityOff>false</turnGravityOff>
      <selfCollide>false</selfCollide>
      <!-- kp: stiffness kd: damping mu1, mu2: friction -->
      <mu1>100.0</mu1>
      <mu2>100.0</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
    </gazebo>
    <!-- the LEDs 
      - {id: 32, name: "origin_marker", options: "pos=3.5,3.0,3.0"}
      - {id: 33, name: "x_axis_marker", options: "pos=268.951,3.0,3.0"}
      - {id: 34, name: "aux1_marker", options: "pos=269.188,199.116,0.58"}
      - {id: 35, name: "aux2_marker", options: "pos=233.578,235.966,0.0"}
      - {id: 36, name: "y_axis_marker", options: "pos=7.356,234.888,3.0"}
      The LEDs themselves are roughy (7.0, 6.0, 4.2)mm in size,
      but we model and render them a simple cubes. The origin is 
      slightly larger.

      Measured positions (fnh):
      origin: 0.0035 0.0030 0.0152
      x_axis: 0.2710 0.0030 0.0150
      y_axis: 0.0035 0.2370 0.0153
      aux_1:  0.2710 0.2020 0.0146    (top border, near left)
      aux_2:  0.2340 0.2385 0.0149    (left border, near top)

      Note: plate thickness (including feet) is 10.5mm, not 10.0.
      Markers should be mounted at iz=0.0105
    -->
    <xacro:phasespace_led name="origin_marker" parent="${name}" size="0.003" >
      <origin xyz="0.0035 0.003 ${0.0105+0.003}" rpy="0 0 0"/>
    </xacro:phasespace_led>
    <xacro:phasespace_led name="x_axis_marker" parent="${name}" size="0.002" >
      <origin xyz="0.2689 0.003 ${0.0105+0.003}" rpy="0 0 0"/>
    </xacro:phasespace_led>
    <xacro:phasespace_led name="y_axis_marker" parent="${name}" size="0.002" >
      <origin xyz="0.00735 0.2349 ${0.0105+0.003}" rpy="0 0 0"/>
    </xacro:phasespace_led>
    <xacro:phasespace_led name="aux1_marker" parent="${name}" size="0.002" >
      <origin xyz="0.2692 0.1991 ${0.0105+0.003}" rpy="0 0 0"/>
    </xacro:phasespace_led>
    <xacro:phasespace_led name="aux2_marker" parent="${name}" size="0.002" >
      <origin xyz="0.2336 0.2359 ${0.0105+0.002}" rpy="0 0 0"/>
    </xacro:phasespace_led>

    <!-- the apriltag on the board, outer size 20cm, inner size 16cm  -->
    <xacro:apriltag_marker namespace="" name="calibration_board_atag122" parent="${name}"
                           family="36h11" ID="122" size="0.20">
       <origin xyz="${0.02+0.20/2} ${0.02+0.20/2} 0.0106" rpy="0 0 -1.571" />
    </xacro:apriltag_marker>

  </xacro:macro>



</robot>
